### PR TITLE
Conformance results for v1.0/IBM Cloud Code Engine

### PR DESCRIPTION
**Pull request by norman465**
| **Title** | |
| ------------------ | -------------------------------------------- |
| **Vendor** | IBM Cloud |
| **Product Name / Version** | Code Engine |
| **Website URL for Product** | https://www.ibm.com/cloud/code-engine |
| Contact | @norman465 or @smoser-ibm |

### CODE REVIEW

**Comment by evankanderson** [comment]
/hold

It sounds like there are some patches to the conformance tests where the tests are checking specific values rather than acceptable ranges; the author will be back from break in a few weeks and can describe more then.

**Comment by evankanderson** [comment]
There is a bug in the list here: https://github.com/knative/specs/pull/94#issuecomment-1128792111

The following tests listed as "Active Tests" should actually be excluded, not included:

```
TestConfigMapVolume
TestSecretVolume
TestProjectedSecretVolume
TestProjectedComplex
TestProjectedServiceAccountToken
```

**Comment by smoser-ibm** [comment]
Some description on what we did, for the upcoming discussion in the Conformance team call: 

1. We ran the two commands as layed out in https://github.com/knative/specs/blob/main/docs/examples/serving/cloud_run.md

```
go test -v -tags=e2e -count=1 ./test/conformance/api/v1/ -disable-logstream=true -test-namespace=qbe92h708ww -alt-test-namespace=qbe92h708ww -tls-test-namespace=qbe92h708ww -namespace=qbe92h708ww -resolvabledomain=true -disable-optional-api=true > ~/conformance-test-api-test.log

go test -v -tags=e2e -count=1 ./test/conformance/runtime/ -disable-logstream=true -test-namespace=qbc7im9tdc5 -alt-test-namespace=qbc7im9tdc5 -tls-test-namespace=qbc7im9tdc5 -namespace=qbc7im9tdc5 -resolvabledomain=true -disable-optional-api=true > ~/conformance-test-runtime-210722.log
```

2. That doesn't work out of the Box, because some values are hardcoded in the test

`https://github.com/knative/serving/blob/main/test/conformance/runtime/cgroup_test.go` requires certain values in 
config-defaults, where Code Engine deviates from. But the test is not configurable 

`https://github.com/knative/serving/blob/main/test/conformance/api/v1/resources_test.go` is setting hardcoded resources that are in conflict with the validating-webhook-serving that we run in production, and again the test is not configurable 

(FWIW, for us to change these in production would have had customer impact, which seems unreasonable) 

The resources have nothing to do woth the API that's under test IMHO, and we believe that we should be able to configure the tests via a flag or config setting. 

3. Furthermore, the test requires A LOT OF rights when running it on K8s. Without having had a deeper look into it,                        it's not clear to us why the tests OOTB need such a lot of access to the resources and what is supposed to be checked with that. 
```
Error from server (Forbidden): replicationcontrollers is forbidden:
Error from server (Forbidden): statefulsets.apps is forbidden: 
Error from server (Forbidden): horizontalpodautoscalers.autoscaling is forbidden:
Error from server (Forbidden): cronjobs.batch is forbidden: 
Error from server (Forbidden): jobs.batch is forbidden:
Error from server (Forbidden): domainmappings.serving.knative.dev is forbidden
```
It those access rights would not be needed, we'd be some steps closer to run the test `as a regular user` and thereore make it more reproducible

**Comment by mchmarny** [comment]
Allowing for these kinds of values (e.g. cpu, memory limits) to be set priory to ensure these are predictable for the test makes sense to me. @smoser-ibm do you want to put together a PR to how you envision this to be implemented?

**Comment by smoser-ibm** [comment]
@norman465 ^^

**Comment by norman465** [comment]
@mchmarny I'll open a PR in the next few days to allow for custom resource specification for conformance tests that need specific resource specifications in order to verify settings (I'm aware of resources_test and cgroup_test). This would allow a deviation from the defaults in `config-defaults`.

**Comment by norman465** [comment]
@evankanderson @mchmarny 
I finally re-ran the conformance tests based on a v1.8.0 [knative](https://github.com/knative/serving/releases/tag/knative-v1.8.0) using these commands:
```
go test -v -tags=e2e -count=1 ./test/conformance/api/v1 -disable-logstream=true -test-namespace=vaw30wzxpbk -alt-test-namespace=vaw30wzxpbk -tls-test-namespace=vaw30wzxpbk -namespace=vaw30wzxpbk -resolvabledomain=true -disable-optional-api=true -custom-memory-requests=500M -custom-memory-limits=500M -custom-cpu-requests=125m -custom-cpu-limits=125m

go test -v -tags=e2e -count=1 ./test/conformance/runtime/ -disable-logstream=true -test-namespace=vaw30wzxpbk -alt-test-namespace=vaw30wzxpbk -tls-test-namespace=vaw30wzxpbk -namespace=vaw30wzxpbk -resolvabledomain=true -disable-optional-api=true -custom-memory-requests=500M -custom-memory-limits=500M -custom-cpu-requests=125m -custom-cpu-limits=125m
```

Additionally, I opened https://github.com/knative/serving/issues/13465.

**Comment by evankanderson** [comment]
/lgtm
/approve

Verified that all the tests listed [in this comment](https://github.com/knative/specs/pull/94#issuecomment-1128792111) are `PASS`ING.

**Pull request merged**
