### PR TITLE
Triggers test plan

### LINKED ISSUE #42: [Eventing - Control Plane] Trigger Lifecycle Manual Test Plan
## Description
This issue describes the creation of a "Manual Testing Plan" for a portion of the Eventing Spec. 

Below is a link to the Spec Sub-heading which this issue is referencing, alongside a template upon which you should base your PR. 

**Link to Spec:** https://github.com/knative/specs/blob/main/specs/eventing/control-plane.md#trigger-lifecycle

**Template:** https://hackmd.io/D1S9NPaRTG2dcyFtdURSww?view

If you have any questions, please reach out in the #conformance channel on Slack 

---

## Acceptance Criteria
- [ ] Contributing to the right place
```
GIVEN I am accepting the PR that closes this issue 
WHEN I inspect the .md file 
THEN I see it is being committed to the /test/test-plan/ folder in the specs repo
```

- [ ] Conformance to Template 
```
GIVEN I am reviewing the submitted .md file 
WHEN I compare it to the template linked above 
THEN I see that the submitted .md conforms to the template 
```

- [ ] Coverage of Spec 
```
GIVEN I am reviewing the submitted .md file
WHEN I compare the .md file to the Trigger Lifecycle subheading in the spec
THEN all of the  "MUST" "MUST NOT" and "REQUIRED" sentences under the Trigger Lifecycle sub-heading are covered within the submitted .md file 
```

- [ ] Coverage of Tests
```
GIVEN I am running each of the tests in the submitted .md file 
AND each test has a expected output
WHEN I am finished running the tests 
THEN all of my tests pass (when compared to the expected output)
AND at least 2 reviewers feel it is properly covering all portions of the spec outlined at the top .md file
```

### PR DESCRIPTION
**Pull request by gabo1208**
Fixes #42

### CODE REVIEW

**Comment by salaboy** [comment]
@gabo1208 great.. this is good progress

/lgtm

**Comment by salaboy** [comment]
@lionelvillard if you know someone interested in reviewing this please let me know..  if not I will merge and we will try to review and send changes with PRs.
I want to have at least the basic sections of the spec covered for future reference.

**Comment by salaboy** [comment]
@gabo1208 if you can create another issue to add the links to the tests from `rekt` that you find, that will be great.. but let's get this PR merged first

**Comment by evankanderson** [comment]
/close

This was an exercise in 1.0 preparation, but we don't need to commit these files at this point.

**Pull request closed without merging**
