### PR TITLE
drop deprecated Revision.Status.imageDigest 

### PR DESCRIPTION
**Pull request by dprotaso**
The field is accessible via the `Revision.Status.containerStatuses[*].imageDigest `

### CODE REVIEW

**Comment by dprotaso** [comment]
cc @knative/trademark-committee

**Comment by evankanderson** [comment]
Is this because we expect the image digests to be resolved when the Revision is created, and for the Revision to be stored with only resolved digests?

If so, is there other language in the spec describing that behavior? I notice that this field is RECOMMENDED but not required, so even if the OSS implementations removes this field, it will still be spec-compliant.

**Comment by dprotaso** [comment]
> Is this because we expect the image digests to be resolved when the Revision is created

Ideally, yes.

> and for the Revision to be stored with only resolved digests?

Only in the status block - we don't override the spec with the result of the resolution.

An additional thing to consider here is potentially changing `ContainerStatus.imageDigest` from `REQUIRED` to `RECOMMENDED` this would enable any additional new fields to be introduced to `ContainerStatus` without requiring the implementor to resolve tags to digest resolution.

**Comment by duglin** [comment]
given the OSS code already did this...
/lgtm

**Comment by dprotaso** [comment]
Technically the alternative option is already in the spec

https://github.com/knative/specs/blob/main/specs/serving/knative-api-specification-1.0.md#containerStatuses

**Pull request merged**
