### PR TITLE
Adding note on immutable broker.spec.config

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

- :broom: Update API type to be `IMMUTABLE`, to match spec:

> ...
and the spec.config field MUST be immutable; the Broker MUST be deleted and re-created to change the implementation class or spec.config. This pattern is chosen to make it clear that changing the implementation class or spec.config is not an atomic operation and that any implementation would be likely to result in event loss during the transition.

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by salaboy** [comment]
@benmoss @evankanderson can I be a collaborator here? I am happy to not have merge rights.. but.. at least reviewer or something :)

**Comment by matzew** [comment]
* Fix for issue: https://github.com/knative/eventing/pull/5682
* conformance test: https://github.com/knative/eventing/pull/5686

**Pull request merged**
