### PR TITLE
Broker Lifecycle conformance test plan proposal

### PR DESCRIPTION
**Pull request by salaboy**
Changes

Adding proposed structure to define the Knative Eventing Conformance Test Plan, including an example for the Control Plane Broker Lifecycle Tests. These tests define a set of resources that needs to be created, the assertions that need to be done, and the expected output that needs to be generated to be able to validate conformance.

The intention of this proposal is to enable people to start automating these tests, also to reach a consensus about what means to test for conformance and how it needs to be done.

🎁 Proposal for Conformance Test Plan structure and manual steps
/kind enhancement

### CODE REVIEW

**Comment by salaboy** [comment]
@benmoss I don't know why but I need your consent here.

**Comment by lionelvillard** [comment]
have you tried rebasing this PR?

**Comment by benmoss** [comment]
Ah because of the code suggestions that you committed, they show up as being coauthored by me.

@googlebot I consent

**Comment by benmoss** [comment]
@googlebot I consent.

**Pull request merged**
