### PR TITLE
Update OWNERS_ALIASES manually while we set up automation

### PR DESCRIPTION
**Pull request by evankanderson**

### CODE REVIEW

**Comment by dprotaso** [comment]
You'll want to update OWNERS to include TOC and steering - otherwise only trademark can approve

**Comment by evankanderson** [comment]
> You'll want to update OWNERS to include TOC and steering - otherwise only trademark can approve

> This PR is APPROVED

But, good point, I'll send a PR to change ownership of the repo.

**Comment by evankanderson** [comment]
I added #113 to change the ownership of the repo to TOC/Steering, after this PR.

**Comment by dprotaso** [comment]
I think #113 has to be part of this PR - otherwise if this merges then the only people who can approve #113 become the non-existent trademark committee

```
  trademark-committee:
  - mchmarny
  - smoser-ibm
  - xtreme-sameer-vohra
```

**Pull request merged**
