### PR TITLE
adding proposed language for conformance criteria

### PR DESCRIPTION
**Pull request by spencerdillard**
# Changes

- New addition of doc that proposes language that was iterated on in a doc by the KTC. :gift:

/kind documentation

**Release Note**

```release-note
Added clear language on conformance criteria definition and evaluation
```

### CODE REVIEW

**Comment by duglin** [comment]
Looks good - can we get a link from the README so that it's easy for people to find it?

**Review by evankanderson — COMMENTED** [review]
/approve

**Comment by evankanderson** [comment]
@duglin to `lgtm`

**Comment by spencerdillard** [comment]
Updated with link from README (apologies for excess commits -- not sure why getting it right was a challenge...)

**Comment by duglin** [comment]
@spencerdillard thanks
/LGTM
/approve

**Pull request merged**
